openapi: 3.0.3
info:
  title: Users API
  description: API for user management operations
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/users
    description: Local development server

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get list of users
      description: Retrieve a paginated list of users with optional filtering
      operationId: getUsers
      security:
        - bearerAuth: [ ]
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: role
          in: query
          description: Filter by role
          required: false
          schema:
            type: string
            enum: [ admin, hr, mentor, intern ]
        - name: status
          in: query
          description: Filter by status
          required: false
          schema:
            type: string
            enum: [ active, blocked, pending ]
        - name: search
          in: query
          description: Search by name or email
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-list-response'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
    post:
      tags:
        - Users
      summary: Create a new user
      description: Create a new user with pending status
      operationId: createUser
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-user-request'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-response'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      description: Retrieve a user by their unique identifier
      operationId: getUserById
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-response'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    user-response:
      $ref: './schemas/user-response.json'
    user-list-response:
      $ref: './schemas/user-list-response.json'
    create-user-request:
      $ref: './schemas/create-user-request.json'
    error-response:
      $ref: './schemas/error-response.json'
